# Generated by Django 3.2.2 on 2021-05-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_alter_domain_record_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
