# Generated by Django 3.2.2 on 2021-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resolver', '0003_delete_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=1000)),
                ('record_type', models.CharField(max_length=1000)),
                ('record_result', models.CharField(max_length=10000)),
            ],
        ),
    ]
