# Generated by Django 3.2.2 on 2021-05-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0006_mxrecord_record_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mxrecord',
            name='record_name',
        ),
    ]
