# Generated by Django 3.2.2 on 2021-05-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0007_remove_mxrecord_record_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='comment',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
