# Generated by Django 3.2.2 on 2021-05-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0008_auto_20210512_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=1000)),
            ],
        ),
    ]
